# environment-related configuration
seed: 4379
episode_num: 1
is_train: &is_train_anchor yes

# episode_num: 30
# is_train: &is_train_anchor no

# the bus dispatched before hold_start_time or after hold_end_time will not be held
hold_start_time: 0
hold_end_time: 10800
episode_duration: 10800

# Only keep Beijing Route 57 in this slimmed version
env_name: 'bj_route_57'
# indicate if there is a schedule for control bus motions
has_schedule: False

# indicate the metrics returned by the environment
metric_names:
  - 'headway_std'
  # virtual bus has slack, so the schedule of buses outside the holding period still consider holds
  # but the bus outside the holding period is not held, so the schedule deviation is not accurate
  # - 'schedule_deviation'
  - 'pax_in_vehicle_wait_time'
  - 'pax_out_vehicle_wait_time'
  - 'queueing_delay'
  #- 'hold_time'

wandb_config:
  # use weights & biases (wandb) to record the experiment or not, yes or no
  is_record_wandb: no
  wandb_project_name: 'open_source_demo'

# choose the running agent: 'Do_Nothing' or 'Naive_DDPG'
running_agent: 'Do_Nothing'
#running_agent: 'Naive_DDPG'


# agent-related configuration
agent_config:
  'Do_Nothing':
    agent_name: 'Do_Nothing'

  'Naive_DDPG':
    agent_name: 'Naive_DDPG'
    is_train: *is_train_anchor
    max_speed: 12
    max_hold_time: 60
    state_size: 3
    hidden_size: [64, ]
    actor_lr: 0.001
    critic_lr: 0.001
    gamma: 0.9
    polya: 0.995
    memory_size: 20000
    update_cycle: 5
    batch_size: 64
    init_noise_level: 0.2
    decay_rate: 0.95
    schedule_headway: 300
    w: 0.03 # penalty for holding time
